# fly.toml app configuration file generated for doko-blog-v2 on 2025-07-24T09:59:13+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doko-blog-v2'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
